import {escapeHtml as e,protocolsFor,filterDevices,matchingFunctions,pinGeometry,validateDevice} from './lib.js';

const main=document.querySelector('#main');
let devices=[],config;
let filters={query:'',kind:'',manufacturer:'',protocol:''};
let view='grid',sort='featured',current=null,selected=[],instance='',defaultsOnly=false,lockedPin=null,pinQuery='';
const protocolOrder=['UART','SPI','I2C','ADC','PWM','DAC','USB','CAN','DEBUG','IRQ','CLOCK'];
const storage={get(key,fallback){try{return JSON.parse(localStorage.getItem('pinatlas:'+key))??fallback;}catch{return fallback;}},set(key,value){try{localStorage.setItem('pinatlas:'+key,JSON.stringify(value));}catch{}}};
const typeColors={gpio:'#52aa91',input:'#699fbd',analog:'#db6572',power:'#d59c4d',ground:'#7f8b93',control:'#7681b1',reserved:'#be6b6b',nc:'#b1b8bd'};
const specLabels={core:'CPU / architecture',clock:'Clock frequency',flash:'Flash memory',sram:'SRAM',eeprom:'EEPROM',logic:'Logic / supply voltage',gpio:'GPIO',adc:'ADC',connectivity:'Interfaces',wireless:'Wireless',usb:'USB',programming:'Programming'};
const orderedProtocols=d=>protocolOrder.filter(p=>protocolsFor(d).includes(p));
const pName=p=>config.protocols[p]?.name||p;
function safeURL(url){try{const u=new URL(url);return u.protocol==='https:'?u.href:'#';}catch{return '#';}}
function applyAppearance(){
  const theme=storage.get('theme',config?.defaultTheme||'light');
  document.documentElement.dataset.theme=theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):theme;
  document.documentElement.dataset.accent=storage.get('accent',config?.defaultAccent||'teal');
  document.body.classList.toggle('compact',storage.get('compact',false));
  document.querySelector('#theme').value=theme;document.querySelector('#accent').value=document.documentElement.dataset.accent;document.querySelector('#compact').checked=storage.get('compact',false);
}
document.querySelector('#settings-button').addEventListener('click',()=>document.querySelector('#settings').showModal());
for(const id of ['theme','accent','compact'])document.querySelector('#'+id).addEventListener('change',event=>{storage.set(id,id==='compact'?event.target.checked:event.target.value);applyAppearance();});
matchMedia('(prefers-color-scheme: dark)').addEventListener('change',applyAppearance);
document.addEventListener('keydown',event=>{if(event.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName)&&!document.querySelector('#settings').open){const s=document.querySelector('#catalog-search');if(s){event.preventDefault();s.focus();}}});

function miniature(d){
  const board=d.layout.style==='board',qfp=d.layout.style==='qfp';
  const fill=board?d.layout.accent:'#2a3843';
  const w=board?70:qfp?82:65,h=board?130:qfp?82:100,y=qfp?29:board?5:20,x=(180-w)/2;
  let pins='';
  const n=board?12:qfp?8:d.pins.length<10?4:8;
  for(let i=0;i<n;i++){
    const py=y+9+i*(h-18)/(n-1);
    pins+=`<rect x="${x-7}" y="${py}" width="10" height="4" rx="1" fill="#bbc4c8"/><rect x="${x+w-3}" y="${py}" width="10" height="4" rx="1" fill="#bbc4c8"/>`;
    if(qfp){const px=x+9+i*(w-18)/(n-1);pins+=`<rect x="${px}" y="${y-7}" width="4" height="10" rx="1" fill="#bbc4c8"/><rect x="${px}" y="${y+h-3}" width="4" height="10" rx="1" fill="#bbc4c8"/>`;}
  }
  return `<svg viewBox="0 0 180 140" aria-hidden="true"><ellipse cx="90" cy="132" rx="47" ry="4" fill="#1b3b5010"/>${pins}<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${board?5:3}" fill="${e(fill)}"/>${board?`<rect x="${x+22}" y="${y-1}" width="26" height="18" rx="2" fill="#bac3c7"/><rect x="${x+21}" y="${y+55}" width="28" height="29" rx="2" fill="#22323c"/><path d="M${x+7} ${y+34}h16v12h24v-12h15M${x+7} ${y+102}h15v-12h27v12h14" fill="none" stroke="#ffffff32" stroke-width="1"/><circle cx="${x+12}" cy="${y+24}" r="3" fill="#d6e9b9"/><text x="90" y="${y+110}" text-anchor="middle" font-size="5" fill="#dfe9e4" font-family="monospace">${e(d.family)}</text>`:`<circle cx="${x+9}" cy="${y+9}" r="3" fill="#80909b"/><text x="90" y="${y+h/2}" text-anchor="middle" font-size="7" fill="#d2dce2" font-family="monospace">${e(d.processor.split('-')[0])}</text><text x="90" y="${y+h/2+12}" text-anchor="middle" font-size="5" fill="#879ba8" font-family="monospace">${e(d.layout.variant)}</text>`}</svg>`;
}
function heroGraphic(){
 return `<svg viewBox="0 0 410 245" aria-hidden="true"><defs><pattern id="hero-dots" width="14" height="14" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".6" fill="currentColor" opacity=".18"/></pattern></defs><rect width="410" height="245" fill="url(#hero-dots)"/><g transform="translate(180 33) rotate(13 40 84)"><rect x="-3" y="5" width="88" height="175" rx="9" fill="#0b433624"/><rect width="82" height="170" rx="7" fill="#327b60"/><rect x="28" y="-3" width="26" height="20" rx="3" fill="#bacbd0"/><rect x="27" y="67" width="30" height="32" rx="2" fill="#1d2f38"/><text x="42" y="85" font-family="monospace" font-size="5" text-anchor="middle" fill="#b7c6c9">RP2040</text><path d="M18 23v33h20v12M65 25v27H49v15M15 111h16v30h36M65 101v20H44" stroke="#93b5a6" stroke-width="1" fill="none"/>${Array.from({length:16},(_,i)=>`<circle cx="8" cy="${21+i*9}" r="2.6" fill="#d9cda1"/><circle cx="74" cy="${21+i*9}" r="2.6" fill="#d9cda1"/>`).join('')}<circle cx="42" cy="120" r="9" fill="none" stroke="#d9e6e0"/><text x="42" y="150" text-anchor="middle" font-family="monospace" font-size="6" fill="#e7f2ec">PICO</text></g><g fill="none" stroke-width="1"><path d="M195 67H138v-8H64" stroke="#3379c6"/><path d="M195 83H124v12H54" stroke="#af67cf"/><path d="M280 138h28v-12h67" stroke="#cd8629"/><path d="M265 170h39v16h65" stroke="#db6572"/></g><g font-family="monospace" font-size="10"><text x="64" y="51" fill="#3379c6">UART0 · TX</text><text x="54" y="111" fill="#af67cf">SPI0 · SCK</text><text x="319" y="118" fill="#cd8629">I2C · SDA</text><text x="319" y="203" fill="#db6572">ADC0</text></g></svg><span class="tag">INTERACTIVE PINOUTS</span><span class="caption">HOVER. HIGHLIGHT. UNDERSTAND.</span>`;
}
function renderCatalog(){
 current=null;document.title=`${config.siteName} — Explore every connection`;
 main.innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span> A REFERENCE FOR BUILDERS</div><h1>${e(config.tagline)}</h1><p>${e(config.description)}</p><div class="hero-stats"><div><strong>${devices.length}</strong><span>Catalog entries</span></div><div><strong>${new Set(devices.map(d=>d.manufacturer)).size}</strong><span>Manufacturers</span></div><div><strong>${new Set(devices.flatMap(protocolsFor)).size}</strong><span>Pin functions</span></div></div></div><div class="hero-visual">${heroGraphic()}</div></section>
 <div class="search-row"><div class="search-wrap"><span class="search-symbol" aria-hidden="true">⌕</span><input id="catalog-search" type="search" value="${e(filters.query)}" placeholder="Search devices, families, or interfaces…" aria-label="Search devices"><kbd class="shortcut">/</kbd></div><div class="view-toggle" aria-label="Catalog view"><button data-view="grid" class="${view==='grid'?'active':''}" aria-label="Grid view" aria-pressed="${view==='grid'}">▦</button><button data-view="list" class="${view==='list'?'active':''}" aria-label="List view" aria-pressed="${view==='list'}">☰</button></div></div>
 <div class="catalog-layout"><aside class="filters" aria-label="Filter catalog"><div class="filter-heading"><h2>Filters</h2><button class="text-button" id="reset-filters">Reset all</button></div><div class="kind-buttons">${[['','All devices'],['board','Development boards'],['chip','Microcontroller chips']].map(([k,l])=>`<button data-kind="${k}" class="${filters.kind===k?'active':''}" aria-pressed="${filters.kind===k}">${l}<span class="count-pill">${devices.filter(d=>!k||d.kind===k).length}</span></button>`).join('')}</div><div class="filter-group"><label class="filter-label" for="manufacturer">Manufacturer</label><select id="manufacturer"><option value="">All manufacturers</option>${[...new Set(devices.map(d=>d.manufacturer))].sort().map(m=>`<option ${filters.manufacturer===m?'selected':''}>${e(m)}</option>`).join('')}</select></div><div class="filter-group protocol-group"><span class="filter-label">Pin function</span><div class="filter-protocols">${protocolOrder.filter(p=>devices.some(d=>protocolsFor(d).includes(p))).map(p=>`<button data-filter-protocol="${p}" class="${filters.protocol===p?'active':''}" aria-pressed="${filters.protocol===p}">${e(pName(p))}</button>`).join('')}</div></div><div class="filter-note">A growing catalog of exact boards and chip packages. Every entry links to manufacturer documentation.<br><br>Missing a device? Add a data file to extend the directory.</div></aside><section aria-label="Device results"><div class="result-head"><span id="result-count" role="status"></span><label>Sort by <select id="sort"><option value="featured">Featured first</option><option value="name">Name A–Z</option><option value="manufacturer">Manufacturer</option></select></label></div><div id="device-results"></div></section></div>`;
 document.querySelector('#sort').value=sort;
 document.querySelector('#catalog-search').addEventListener('input',event=>{filters.query=event.target.value;renderResults();});
 document.querySelector('#manufacturer').addEventListener('change',event=>{filters.manufacturer=event.target.value;renderResults();});
 document.querySelector('#sort').addEventListener('change',event=>{sort=event.target.value;renderResults();});
 document.querySelector('#reset-filters').addEventListener('click',()=>{filters={query:'',kind:'',manufacturer:'',protocol:''};renderCatalog();});
 main.querySelectorAll('[data-kind]').forEach(b=>b.addEventListener('click',()=>{filters.kind=b.dataset.kind;main.querySelectorAll('[data-kind]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});renderResults();}));
 main.querySelectorAll('[data-filter-protocol]').forEach(b=>b.addEventListener('click',()=>{filters.protocol=filters.protocol===b.dataset.filterProtocol?'':b.dataset.filterProtocol;main.querySelectorAll('[data-filter-protocol]').forEach(x=>{x.classList.toggle('active',x.dataset.filterProtocol===filters.protocol);x.setAttribute('aria-pressed',x.dataset.filterProtocol===filters.protocol);});renderResults();}));
 main.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;storage.set('view',view);main.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});renderResults();}));
 renderResults();
}
function renderResults(){
 const result=filterDevices(devices,filters).sort((a,b)=>sort==='manufacturer'?a.manufacturer.localeCompare(b.manufacturer)||a.name.localeCompare(b.name):sort==='name'?a.name.localeCompare(b.name):Number(b.id===config.featuredDevice)-Number(a.id===config.featuredDevice)||Number(b.kind==='board')-Number(a.kind==='board')||a.name.localeCompare(b.name));
 document.querySelector('#result-count').innerHTML=`<strong>${result.length} ${result.length===1?'device':'devices'}</strong> ${result.length===devices.length?'in the starter catalog':`of ${devices.length} entries`}`;
 document.querySelector('#device-results').innerHTML=result.length?`<div class="device-grid ${view==='list'?'list':''}">${result.map(d=>`<a class="device-card" href="#/device/${e(d.id)}" aria-label="Explore ${e(d.name)}, ${e(d.layout.variant)}"><div class="device-art"><span class="type-badge">${d.kind==='board'?'DEV BOARD':'MCU CHIP'}</span>${miniature(d)}</div><div class="card-body"><div class="card-maker"><span>${e(d.manufacturer)}</span><span>↗</span></div><h3>${e(d.name)}</h3><div class="card-variant">${e(d.layout.variant)}</div><div class="card-specs"><span>${e(d.specs.clock.split(' · ')[0])}</span><span>${e(d.specs.logic.split(' supply')[0])}</span><span>${e(d.specs.flash.split(' external')[0])} flash</span><span>${e(d.specs.sram)} RAM</span></div><div class="chips">${orderedProtocols(d).filter(p=>['UART','SPI','I2C','ADC','PWM','USB'].includes(p)).slice(0,5).map(p=>`<span class="chip">${e(pName(p))}</span>`).join('')}${d.specs.wireless&&d.specs.wireless!=='None'?'<span class="chip">Wi-Fi</span>':''}</div></div><div class="card-footer"><span>${d.pins.length} ${d.kind==='board'?'header connections':'package pins'}</span><span class="card-arrow">→</span></div></a>`).join('')}</div>`:'<div class="empty"><h2>No matching devices</h2><p>Try a broader search or reset the filters.</p><button id="empty-reset">Reset filters</button></div>';
 document.querySelector('#empty-reset')?.addEventListener('click',()=>{filters={query:'',kind:'',manufacturer:'',protocol:''};renderCatalog();});
}
function renderDevice(d){
 current=d;selected=[];instance='';defaultsOnly=false;lockedPin=null;pinQuery='';document.title=`${d.name} pinout — ${config.siteName}`;
 main.innerHTML=`<div class="breadcrumb"><a href="#/">All devices</a><span>/</span><span>${e(d.manufacturer)}</span><span>/</span><span>${e(d.name)}</span></div><section class="detail-heading"><div><div class="detail-title-meta"><span class="type-badge">${d.kind==='board'?'Development board':'Microcontroller chip'}</span><span class="eyebrow">${e(d.layout.variant)}</span></div><h1>${e(d.name)}</h1><p>${e(d.description)}</p></div><div class="detail-actions"><button id="share-device" class="button-link">Copy link ↗</button><a href="${e(safeURL(d.sources[0].url))}" target="_blank" rel="noopener noreferrer" class="button-link primary">Official reference ↗</a></div></section><section class="quick-specs" aria-label="Quick specifications">${['core','clock','flash','sram','logic'].map(k=>`<div><small>${e(specLabels[k])}</small><strong>${e(d.specs[k]||'See datasheet')}</strong></div>`).join('')}</section>
 <div class="pin-workspace"><aside class="panel panel-pad protocol-panel"><h2>Highlight pin functions</h2><p class="panel-intro">Select one or more interfaces to see matching pins.</p><div class="protocol-buttons">${orderedProtocols(d).map(p=>`<button class="protocol-button" data-protocol="${p}" aria-pressed="false" style="--protocol:${e(config.protocols[p].color)}" title="${e(config.protocols[p].description)}"><span><i class="color-dot"></i>${e(pName(p))}</span><small>${d.pins.filter(a=>a.functions.some(f=>f.protocol===p)).length}</small></button>`).join('')}</div><label class="instance-filter" for="instance">Peripheral instance<select id="instance"><option value="">All instances</option></select></label>${d.pins.some(p=>p.functions.some(f=>f.mapping==='routable'))?'<label class="checkbox-label"><input type="checkbox" id="defaults-only"> Common default routes only</label>':''}<button id="clear-highlight" class="text-button" style="margin-top:17px">Clear highlights</button><p class="protocol-note" id="protocol-note">Hover a pin for details, click to keep it selected. On touch screens, tap a pin. Keyboard: Tab, then Enter.</p></aside><section class="panel viewer-panel" aria-label="Interactive pinout"><div class="viewer-header"><h2>Interactive pinout</h2><span>TOP VIEW · NOT TO SCALE</span></div><div class="diagram-canvas" id="diagram"></div><div class="viewer-foot">${[['gpio','GPIO'],['power','Power'],['ground','Ground'],['control','Control'],['reserved','Reserved']].filter(([t])=>d.pins.some(p=>p.type===t)).map(([t,l])=>`<span><i class="type-dot" style="background:${typeColors[t]}"></i>${l}</span>`).join('')}</div><p class="panel-intro" style="padding:12px 18px;margin:0">${e(d.layout.orientation)}</p></section><aside class="panel panel-pad pin-detail" id="pin-detail" aria-label="Selected pin details"></aside></div>
 <details class="panel device-notes" open><summary>Device notes & pin-mapping rules</summary><ul>${d.notes.map(n=>`<li>${e(n)}</li>`).join('')}</ul></details><div class="lower-details"><section class="panel panel-pad"><h2>Technical specifications</h2><table class="spec-table"><tbody>${Object.entries(d.specs).map(([k,v])=>`<tr><th scope="row">${e(specLabels[k]||k)}</th><td>${e(v)}</td></tr>`).join('')}</tbody></table></section><section class="panel panel-pad"><h2>Manufacturer documentation</h2><p class="panel-intro">Reference the exact package or board revision before wiring.</p>${d.sources.map(s=>`<a class="source-link" href="${e(safeURL(s.url))}" target="_blank" rel="noopener noreferrer">${e(s.title)} ↗<small>${e(new URL(s.url).hostname)}</small></a>`).join('')}<p class="coverage">${e(d.coverage)}<br><br>Data reviewed: ${e(d.reviewed)}. Community reference; not affiliated with the manufacturers.</p><button class="button-link" id="download-data">Download device JSON ↓</button></section></div><section class="panel pin-table-section"><div class="table-heading"><h2>Pin reference <span class="chip">${d.pins.length} connections</span></h2><input id="pin-search" type="search" placeholder="Find a pin, signal, or instance…" aria-label="Search pin reference"></div><div class="table-scroll" id="pin-table"></div></section>`;
 main.querySelectorAll('[data-protocol]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.protocol;selected=selected.includes(p)?selected.filter(x=>x!==p):[...selected,p];instance='';updateHighlights();}));
 document.querySelector('#instance').addEventListener('change',event=>{instance=event.target.value;updateHighlights(false);});
 document.querySelector('#defaults-only')?.addEventListener('change',event=>{defaultsOnly=event.target.checked;updateHighlights();});
 document.querySelector('#clear-highlight').addEventListener('click',()=>{selected=[];instance='';defaultsOnly=false;const cb=document.querySelector('#defaults-only');if(cb)cb.checked=false;updateHighlights();});
 document.querySelector('#pin-search').addEventListener('input',event=>{pinQuery=event.target.value;renderPinTable();});
 document.querySelector('#share-device').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('Device link copied');}catch{toast('Copy the device link from your browser address bar');}});
 document.querySelector('#download-data').addEventListener('click',()=>{const u=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=d.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);});
 renderDiagram();renderPinDetail();renderPinTable();updateHighlights();
}
function renderDiagram(){
 const d=current,{width,height,body:b,pins}=pinGeometry(d),board=d.layout.style==='board',qfp=d.layout.style==='qfp';
 let body=`<rect x="${b.x}" y="${b.y}" width="${b.w}" height="${b.h}" rx="${board?10:5}" class="${board?'board-body':'chip-body'}"/>`;
 if(board){
  const usbBottom=d.family==='ESP32',usbY=usbBottom?b.y+b.h-18:b.y-7;
  body+=`<rect x="${b.x+b.w/2-20}" y="${usbY}" width="40" height="25" rx="3" fill="#bdc8cd" stroke="#83929b"/><rect x="${b.x+47}" y="${b.y+b.h/2-34}" width="66" height="68" rx="3" fill="#24343d"/><text x="${width/2}" y="${b.y+b.h/2}" text-anchor="middle" class="diagram-chip-text">${e(d.processor)}</text><path d="M${b.x+22} ${b.y+56}h25v${Math.max(10,b.h/2-106)}M${b.x+b.w-22} ${b.y+70}h-25v${Math.max(10,b.h/2-120)}M${b.x+27} ${b.y+b.h-55}h25v-40h45" fill="none" stroke="#e6ffef28" stroke-width="2"/><circle cx="${b.x+21}" cy="${b.y+31}" r="5" fill="#d7e2b8"/><text x="${width/2}" y="${b.y+b.h-37}" text-anchor="middle" class="diagram-brand">${e(d.family)}</text>`;
 }else{
  body+=`<circle cx="${b.x+12}" cy="${b.y+12}" r="4" fill="#a1b0b8"/>${qfp?'':`<path d="M${width/2-17} ${b.y}a17 17 0 0 0 34 0" stroke="#8498a3" fill="none" stroke-width="2"/>`}<text x="${width/2}" y="${height/2}" text-anchor="middle" class="diagram-brand" font-size="${qfp?14:11}">${e(d.processor)}</text><text x="${width/2}" y="${height/2+22}" text-anchor="middle" class="diagram-chip-text">${e(d.layout.variant)}</text>`;
 }
 const groups=pins.map(p=>{
  const left=p.side==='left',right=p.side==='right',top=p.side==='top',horizontal=left||right;
  const lx=horizontal?p.x+(left?-31:31):p.x,ly=horizontal?p.y+4:p.y+(top?-33:43),anchor=left?'end':right?'start':'middle';
  const numberX=horizontal?p.x+(left?13:-13):p.x,numberY=horizontal?p.y+3:p.y+(top?15:-10);
  return `<g class="svg-pin" data-pin="${e(p.id)}" tabindex="0" role="button" aria-label="${e(p.label)}, pin ${e(p.id)}, ${e(p.type)}" aria-pressed="false"><title>${e(p.label)} · ${e(p.id)}${p.functions.length?' · '+e(p.functions.map(f=>f.instance+' '+f.signal).join(', ')):''}</title><rect x="${horizontal?(left?p.x-120:p.x-8):p.x-12}" y="${horizontal?p.y-12:(top?p.y-110:p.y-8)}" width="${horizontal?128:24}" height="${horizontal?24:118}" fill="transparent"/><line x1="${p.x}" y1="${p.y}" x2="${horizontal?p.x+(left?-23:23):p.x}" y2="${horizontal?p.y:p.y+(top?-23:23)}" class="pin-line"/><rect x="${p.x-5}" y="${p.y-5}" width="10" height="10" rx="${board?2:1}" class="pin-pad" style="fill:${typeColors[p.type]}"/><text x="${lx}" y="${ly}" text-anchor="${anchor}" class="pin-label" ${horizontal?'':`transform="rotate(-90 ${lx} ${ly})"`}>${e(p.label)}</text><text x="${numberX}" y="${numberY}" text-anchor="middle" class="pin-number">${e(p.id)}</text></g>`;
 }).join('');
 document.querySelector('#diagram').innerHTML=`<svg viewBox="0 0 ${width} ${height}" style="--board-accent:${e(d.layout.accent)}" role="group" aria-label="${e(d.name)} interactive top-view pinout">${body}${groups}</svg>`;
 main.querySelectorAll('.svg-pin').forEach(g=>{
  const p=d.pins.find(p=>p.id===g.dataset.pin);
  g.addEventListener('pointerenter',()=>{if(!lockedPin)renderPinDetail(p);});
  g.addEventListener('pointerleave',()=>{if(!lockedPin)renderPinDetail();});
  g.addEventListener('focus',()=>{if(!lockedPin)renderPinDetail(p);});
  g.addEventListener('blur',()=>{if(!lockedPin)renderPinDetail();});
  g.addEventListener('click',()=>selectPin(p));
  g.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();selectPin(p);}if(event.key==='Escape'){lockedPin=null;updatePinSelection();renderPinDetail();}});
 });
}
function selectPin(p){lockedPin=lockedPin?.id===p.id?null:p;updatePinSelection();renderPinDetail(lockedPin);}
function updatePinSelection(){main.querySelectorAll('.svg-pin').forEach(g=>{const active=g.dataset.pin===lockedPin?.id;g.classList.toggle('selected',active);g.setAttribute('aria-pressed',active);});main.querySelectorAll('[data-table-pin]').forEach(r=>r.classList.toggle('active',r.dataset.tablePin===lockedPin?.id));}
function renderPinDetail(p=lockedPin){
 const box=document.querySelector('#pin-detail');if(!box)return;
 if(!p){box.innerHTML='<div class="pin-detail-top"><span>PIN INSPECTOR</span><span>↗</span></div><div class="detail-placeholder"><span class="big-pin">⌖</span>Explore a connection<p style="margin:12px 0 0;font-size:11px">Hover any pin to see its name, function, and notes. Click to keep it here.</p></div>';return;}
 box.innerHTML=`<div class="pin-detail-top"><span>${lockedPin?'SELECTED PIN':'PIN PREVIEW'}</span><span>${e(p.id)}</span></div><h3>${e(p.label)}</h3><span class="pin-type">${e(p.type)}${p.gpio?' · '+e(p.gpio):''}</span>${p.notes?`<p class="pin-note">${e(p.notes)}</p>`:''}<div>${p.functions.length?p.functions.map(f=>`<div class="function-row"><span class="chip" style="color:${e(config.protocols[f.protocol].color)}">${e(pName(f.protocol))}</span><span>${e(f.signal)}<small>${e(f.instance)} · ${e(f.mapping==='usi'?'USI mode':f.mapping)}</small></span></div>`).join(''):'<p class="pin-note">No peripheral functions listed for this connection.</p>'}</div>${lockedPin?'<p class="selection-message">Click the selected pin again to release it.</p><button id="release-pin" class="text-button">Clear selection</button>':''}`;
 document.querySelector('#release-pin')?.addEventListener('click',()=>{lockedPin=null;updatePinSelection();renderPinDetail();});
}
function updateHighlights(updateInstances=true){
 if(updateInstances){
  const opts=[...new Set(current.pins.flatMap(p=>matchingFunctions(p,selected,'',defaultsOnly).map(f=>f.instance)))].sort();
  const select=document.querySelector('#instance');if(!opts.includes(instance))instance='';select.innerHTML='<option value="">All instances</option>'+opts.map(i=>`<option value="${e(i)}" ${i===instance?'selected':''}>${e(i)}</option>`).join('');select.disabled=!selected.length;
 }
 main.querySelectorAll('[data-protocol]').forEach(b=>{const active=selected.includes(b.dataset.protocol);b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});
 const active=selected.length>0;
 let count=0;
 main.querySelectorAll('.svg-pin').forEach(g=>{
  const p=current.pins.find(p=>p.id===g.dataset.pin),f=matchingFunctions(p,selected,instance,defaultsOnly),highlight=active&&f.length>0;
  g.classList.toggle('highlight',highlight);g.classList.toggle('dim',active&&!highlight);
  g.style.setProperty('--pin-color',highlight?config.protocols[f[0].protocol].color:typeColors[p.type]);
  g.querySelector('.pin-pad').style.fill=highlight?config.protocols[f[0].protocol].color:typeColors[p.type];
  g.setAttribute('aria-label',`${p.label}, pin ${p.id}, ${highlight?'matching '+selected.join(', ')+', ':''}${p.type}`);if(highlight)count++;
 });
 const hasRoutable=current.pins.some(p=>matchingFunctions(p,selected,instance,defaultsOnly).some(f=>f.mapping==='routable'));
 document.querySelector('#protocol-note').textContent=active?`${count} matching connections. ${hasRoutable?'These include GPIO-matrix routing candidates. Enable default routes to narrow the view.':'Highlights show available functions; shared pins and configuration may prevent simultaneous use.'}`:'Hover a pin for details, click to keep it selected. On touch screens, tap a pin. Keyboard: Tab, then Enter.';
 renderPinTable();
}
function renderPinTable(){
 const q=pinQuery.toLowerCase().trim();
 const pins=current.pins.filter(p=>[p.label,p.id,p.gpio||'',p.type,...p.functions.flatMap(f=>[f.protocol,f.instance,f.signal])].join(' ').toLowerCase().includes(q));
 document.querySelector('#pin-table').innerHTML=`<table class="pin-table"><thead><tr><th scope="col">Pin / header</th><th scope="col">Signal</th><th scope="col">Type</th><th scope="col">Common functions</th><th scope="col">Notes</th></tr></thead><tbody>${pins.map(p=>`<tr data-table-pin="${e(p.id)}"><td>${e(p.id)}</td><td><button data-select-pin="${e(p.id)}">${e(p.label)}</button></td><td>${e(p.type)}</td><td>${p.functions.map(f=>`<span class="chip" ${selected.includes(f.protocol)&&matchingFunctions(p,selected,instance,defaultsOnly).includes(f)?`style="color:${e(config.protocols[f.protocol].color)};border-color:${e(config.protocols[f.protocol].color)}"`:''}>${e(f.instance)} ${e(f.signal)}</span>`).join('')||'—'}</td><td>${e(p.notes)||'—'}</td></tr>`).join('')||'<tr><td colspan="5">No matching pins.</td></tr>'}</tbody></table>`;
 main.querySelectorAll('[data-select-pin]').forEach(b=>b.addEventListener('click',()=>{selectPin(current.pins.find(p=>p.id===b.dataset.selectPin));document.querySelector('#pin-detail').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});}));updatePinSelection();
}
function renderAbout(){
 current=null;document.title=`About & data — ${config.siteName}`;
 main.innerHTML=`<section class="about"><div class="eyebrow">A GROWING OPEN REFERENCE</div><h1>Built to keep growing.</h1><p>Pin Atlas connects a searchable device directory with an interactive pinout viewer. The current release contains ${devices.length} curated entries, with separate records for development boards and exact chip packages.</p><div class="about-grid"><div class="panel"><h2>Understand the pinout</h2><p>Hover or focus a pin for details. Click or tap to select it. Choose UART, SPI, I²C, or another function to highlight matching pins, then narrow the view to a peripheral instance.</p><p>A highlight shows a function that is available on a pin. It does not configure the hardware or guarantee that all highlighted functions can be used together.</p></div><div class="panel"><h2>Keep the data precise</h2><p>Every device lists the package or board revision, pin-map orientation, coverage, and manufacturer sources. Main board headers are shown; programming headers are excluded where the entry says so.</p><p>Check the official documentation for electrical limits, alternate-function remaps, errata, and a final wiring plan.</p></div></div><div class="panel"><h2>Add a device without changing the viewer</h2><ol><li>Copy an existing file in <code>data/devices/</code>, or use <code>node scripts/new-device.mjs</code> to create a blank template.</li><li>Set the exact model, revision or package, specifications, sources, and pin data.</li><li>Choose a board, DIP, or QFP layout; each pin stores its side and position.</li><li>Run <code>npm test</code> and <code>npm run build</code>. The catalog index updates automatically.</li><li>Commit the change. The included GitHub Pages workflow deploys the updated static site.</li></ol><p>Site name, homepage text, default appearance, featured device, and peripheral colors live in <code>data/config.json</code>. Layout and typography use CSS variables in <code>styles.css</code>. See <code>docs/CUSTOMIZATION.md</code> for the data contract and extension guide.</p></div><div class="panel" style="margin-top:20px"><h2>Catalog coverage</h2><p>This is a starter catalog, not an exhaustive inventory of every microcontroller. It includes Arduino UNO R3 and classic Nano, Pico / Pico W / Pico 2, ESP32-DevKitC V4, ATmega328P, six tinyAVR variants, and STM32F103C8T6.</p><p>The data lists common functions. STM32 remapped routes are not included; ESP32 distinguishes routable GPIO-matrix candidates from common defaults; tinyAVR USI modes are identified explicitly.</p><a class="button-link" href="#/">Explore the catalog →</a></div></section>`;
}
function toast(message){document.querySelector('.toast')?.remove();const div=document.createElement('div');div.className='toast';div.setAttribute('role','status');div.textContent=message;document.body.append(div);setTimeout(()=>div.remove(),3000);}
function route(){
 const path=location.hash.slice(1)||'/';
 document.querySelectorAll('.nav-link').forEach(a=>a.classList.toggle('active',a.hash==='#'+(path==='/about'?'/about':'/')));
 if(path==='/about')renderAbout();else if(path.startsWith('/device/')){const id=path.slice(8),d=devices.find(d=>d.id===id);if(d)renderDevice(d);else {current=null;main.innerHTML='<div class="empty"><h1>Device not found</h1><p>This model is not in the catalog yet.</p><a class="button-link" href="#/">Back to devices</a></div>';}}else renderCatalog();
 window.scrollTo(0,0);
}
async function start(){
 try{
  const read=async path=>{const r=await fetch(path);if(!r.ok)throw new Error(`Could not load ${path}`);return r.json();};
  const [c,index]=await Promise.all([read('./data/config.json'),read('./data/catalog.json')]);config=c;
  for(const entry of index.devices)if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(entry.id))throw new Error('Invalid catalog record');
  devices=await Promise.all(index.devices.map(x=>read(`./data/devices/${x.id}.json`)));
  for(const d of devices){const errors=validateDevice(d,config.protocols);if(errors.length)throw new Error(`${d.name}: ${errors.join(', ')}`);}
  const base=document.querySelector('.brand');base.querySelector('span:last-child').innerHTML=`${e(config.siteName.replace(/\s/g,'').slice(0,3).toLowerCase())}<span class="brand-light">${e(config.siteName.replace(/\s/g,'').slice(3).toLowerCase())}</span><small>THE MICROCONTROLLER DIRECTORY</small>`;
  base.setAttribute('aria-label',config.siteName+' home');view=storage.get('view','grid');applyAppearance();route();window.addEventListener('hashchange',route);
 }catch(error){main.innerHTML=`<div class="empty"><h1>The catalog could not load</h1><p>${e(error.message)}</p><p>Serve this folder over HTTP, or run the build and publish it with GitHub Pages. Opening index.html directly from a local file cannot load the JSON catalog.</p><button id="retry">Try again</button></div>`;document.querySelector('#retry').addEventListener('click',()=>location.reload());}
}
start();
